# installer
[tools.claude]
type = "installer"
url = "https://claude.ai/install.sh"
update_command = "claude update"
version_regex = "([\\d.]+)"

[tools.markado]
type = "github_release"
repo = "halkn/markado"
version_regex = "([\\d.]+)"
