#!/usr/bin/env bash
#MISE hide=true
set -euo pipefail
rm -rf "${TMPDIR:-/tmp}"/luals-check
VIMRUNTIME="$(nvim --clean --headless -c 'lua io.write(vim.env.VIMRUNTIME)' +q 2>/dev/null)" \
  lua-language-server --check=.config/nvim --checklevel=Warning \
  --logpath="${TMPDIR:-/tmp}"/luals-check/log --metapath="${TMPDIR:-/tmp}"/luals-check/meta
rm -rf "${TMPDIR:-/tmp}"/luals-check
